popup_more_info_button_message: 'Näytä evästeet'
popup_find_more_button_message: 'Näytä evästeet'
popup_info:
  value: '<h2>Hel.fi käyttää evästeitä</h2><p>Tämä sivusto käyttää välttämättömiä evästeitä suorituskyvyn varmistamiseksi sekä yleisen käytön seurantaan. Lisäksi käytämme kohdennusevästeitä käyttäjäkokemuksen parantamiseksi, analytiikkaan ja kohdistetun sisällön näyttämiseen.</p>'
popup_link: /cookie-information-and-settings
save_preferences_button_label: 'Hyväksy valitut evästeet'
