_core:
  default_config_hash: UvSCt3S_NldJPFzvhSNOy9vWoPPFhmsmTC12vtVss9s
preset_accent_color: blue
preset_focus_color: gin
enable_darkmode: false
classic_toolbar: vertical
icon_default: true
icon_path: ''
high_contrast_mode: false
show_user_theme_settings: false
third_party_settings:
  shortcut:
    module_link: true
