front_page_title: 'Culture and leisure'
asset_path: kuva-assets
prefixes:
  en: culture-and-leisure
  fi: kulttuuri-ja-vapaa-aika
  sv: kultur-och-fritid
  ru: culture-and-leisure
  zxx: culture-and-leisure
